name: HEXO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "DonaldWu"
          git config --global user.email "deirenwu1101@gmail.com"

      - name: Install dependencies
        run: |
          git clone https://github.com/DonaldlWu/hexo-theme-freemind.386.git themes/freemind.386
          npm i -g hexo-cli
          npm install hexo-generator-search --save
          npm i

      - name: Deploy hexo
        run: |
          hexo g -d
